# Generated by Django 4.1.1 on 2022-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subhub',
            name='description',
            field=models.TextField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subhub',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
    ]
