# Generated by Django 4.1.1 on 2022-10-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.TextField(max_length=64),
        ),
        migrations.AlterField(
            model_name='subhub',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
