# Generated by Django 4.1.1 on 2022-10-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='s', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='subhub',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
